# Generated by Django 3.1.7 on 2021-04-01 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20210401_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='conten',
            new_name='content',
        ),
    ]
