# Generated by Django 3.1.7 on 2021-04-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('title',)},
        ),
        migrations.RenameField(
            model_name='note',
            old_name='text',
            new_name='title',
        ),
        migrations.AddField(
            model_name='note',
            name='conten',
            field=models.TextField(blank=True, null=True),
        ),
    ]
